config/routes.rb
Jl0432Jie::Application.routes.draw do

  get "test/index"

  get "home/index"

  resources :share_type

  resources :posts

  root :to => "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title
end

app/models/share_type.rb
class ShareType < ActiveRecord::Base
  # attr_accessible :title, :body
  set_table_name  "t_share_type"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json:@posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json:@post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json:@post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice:'Post was successfully created.' }
        format.json { render json:@post, status::created, location:@post }
      else
        format.html { render action:"new" }
        format.json { render json:@post.errors, status::unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice:'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action:"edit" }
        format.json { render json:@post.errors, status::unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/share_types_controller.rb
class ShareTypesController < ApplicationController
  def create
    @ShareType = ShareType.new(params[:ShareType])
    respond_to do |format|
      if @ShareType.save
        format.html { redirect_to @ShareType, notice:'shareType was successfully created.' }
        format.json { render json:@ShareType, status::created, location:@ShareType }
      else
        format.html { render action:"new" }
        format.json { render json:@ShareType.errors, status::unprocessable_entity }
      end
    end
  end

  def new
    @ShareType = ShareType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json:@ShareType }
    end
  end

  def edit
  end

  def delete
  end

  def index
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/share_type_helper.rb
module ShareTypeHelper
end

app/helpers/share_types_helper.rb
module ShareTypesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jl0432Jie</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>


<%= link_to 'New ShareType', share_types_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/share_type/_shareform.html.erb
<%= form_for(@ShareType) do |f| %>
    <% if @ShareType.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ShareType.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @ShareType.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :type_name %><br />
      <%= f.text_field :type_name %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/share_types/_share_type_form.html.erb
<%= form_for(@ShareType) do |f| %>
    <% if @ShareType.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ShareType.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @ShareType.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :TYPE_NAME %><br />
      <%= f.text_field :TYPE_NAME%>
    </div>
    <div class="field">
      <%= f.label :TYPE_CODE %><br />
      <%= f.text_field :TYPE_CODE %>
    </div>
    <div class="field">
      <%= f.label :TYPE_DESC %><br />
      <%= f.text_field :TYPE_DESC %>
    </div>


    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/share_types/create.html.erb
<h1>ShareTypes#create</h1>
<p>Find me in app/views/share_types/create.html.erb</p>

app/views/share_types/delete.html.erb
<h1>ShareTypes#delete</h1>
<p>Find me in app/views/share_types/delete.html.erb</p>

app/views/share_types/edit.html.erb
<h1>ShareTypes#edit</h1>
<p>Find me in app/views/share_types/edit.html.erb</p>

app/views/share_types/index.html.erb
<%= link_to 'New share_type', new_share_type_path %>

app/views/share_types/new.html.erb
<%= render 'share_type_form' %>